### ISSUE TITLE
Can you please add these two labels for PR to be accepted?

### ISSUE THREAD

**Issue by achoudh5** [aryangulati/Hacktoberfest2020#36]
The PR's which are closed are missing tags #21

https://hacktoberfest.digitalocean.com/hacktoberfest-update

Hi

Can you please add two labels:-

At you repo, main page-> hacktoberfest label

Closed PR's-> label->hacktoberfest-accepted

**Comment by aryangulati** [comment]
We’re making Hacktoberfest opt-in only for projects – which maintainers can do simply by adding the ‘hacktoberfest’ topic to a repository.
please see carefully topic is already added to the repo
