### ISSUE TITLE
Replace all absolute paths in readmes to relative

### ISSUE THREAD

**Issue by Zircoz** [aryangulati/Hacktoberfest2020#42]
The guideline of using relative path was made after many significant contributions were made. And we forgot checking paths when the table of languages in hello was made. So, if someone can fix this discrepancy it would be great.

**Comment by khushi2912** [comment]
Can you assign this to me?

**Comment by Exter-dg** [comment]
I would like to work on this. Can you assign this to me?

**Comment by Zircoz** [comment]
Done @Exter-dg

**Comment by Zircoz** [comment]
Good work @Exter-dg
